[project]
name = "timeout-tools"
description = "Time Out Dev Tools"
version = "0.5.0"
authors = [
    { name = "Keith Harvey", email = "keith.harvey@timeout.com" }
]
dependencies = [
   "argparse",
]

[project.scripts]
timeout-tools =  "timeout_tools.cli:main"
